export const hangoutCopy = {
  en: {
    title: 'pick a Hangout.', back: 'back to your Thing', same_brain: 'Same Brain', know_me: 'Know Me', this_or_that: 'This or That', hot: 'Hot',
    sameBrainDescription: 'Pick separately. See if you matched.', knowMeDescription: 'Predict what the other person chose.',
    thisOrThatDescription: 'Vote which of you fits it more.', hotDescription: 'Flirty to spicy prompts, only at a level you both accept.',
    chooseLevel: 'choose your Hot limit.', privateChoice: 'we only show the shared level.', flirty: 'Flirty', bold: 'Bold', spicy: 'Spicy', kitkat: 'KitKat',
    waitingConsent: 'waiting for both choices…', sharedLevel: 'shared level', start: 'start →', ourDeck: 'Our Deck',
    ourDeckDescription: 'Make your own private cards, then mix them together.', makeBatch: 'make your batch.', cardsEach: '3 cards each.',
    mixed: 'we’ll mix them together.', anonymous: 'no names attached.', addCard: 'add card', finishBatch: 'finish my batch',
    yourCards: 'your cards', theirCards: 'their cards', waitingBatch: 'waiting for the other batch…', batchReady: 'both batches are ready.',
    foundation: 'This Hangout is ready for its game engine.', state: 'status', retry: 'try again', busy: 'one moment…',
    sameBrainIntro: 'Eight quick picks. Answer separately, then reveal together.', begin: 'same brain →', round: 'round',
    waitingPartner: 'waiting for them…', answerLocked: 'answer locked.', match: 'MATCH', sameBrain: 'same brain.',
    notThisTime: 'not this time.', youPicked: 'you picked', theyPicked: 'they picked', next: 'next one →',
    finalLine: 'that was', matched: 'matched', bestStreak: 'best streak', seeSpace: 'see Space', backThing: 'back to Thing',
    togetherQuestion: 'are you together right now?', together: "we’re together", apart: "we’re apart", contextFixed: 'this stays the same for this Hangout.',
    knowMeIntro: 'Eight predictions. Take turns choosing and guessing.', thisOrThatIntro: 'Eight questions. Vote privately on who fits each one.',
    subjectPrompt: 'what would you pick?', predictorPrompt: 'what do you think they picked?', votePrompt: 'who fits this more?',
    gotIt: 'you got it.', missedIt: 'not this one.', agreed: 'you agreed.', split: 'split decision.',
    predictions: 'predictions', correct: 'correct', agreements: 'agreements',
    hotIntro: 'Start Flirty. Turning it up always takes both of you.', completePrompt: 'done', skip: 'skip', finishHere: 'finish here',
    wannaBold: 'wanna turn it up?', wannaSpicy: 'keep going?', kitkatWait: 'wait…', kitkatMore: "there’s one more.",
    stayFlirty: 'stay flirty', goBold: 'go bold', stayBold: 'stay bold', goSpicy: 'go spicy', openKitkat: 'open KitKat', maybeNot: 'maybe not',
    stayingHere: 'staying here :)', levelUp: 'you both said yes.', waitingVote: 'waiting for their private choice…', prompts: 'prompts', reached: 'reached',
    said: 'said', youGuessed: 'you guessed', wannaExplain: 'wanna say why?', addThought: 'add a thought', keepGoing: 'keep going →',
    picked: 'picked', noted: 'noted.', yourMove: 'your move.', useIt: 'use it →', answerBack: 'answer back →', theirTurn: 'their turn →',
    turn: "{name}'s turn", howWell: 'how well do you know {name}?', choosing: '{name} is choosing…', whatPicked: 'what do you think they picked?', waitingMove: 'waiting for {name} to react…',
    rememberThis: 'remember this?', youFoundIt: 'you found it.', oneMoreDoor: 'one more door.',
  },
  es: {
    title: 'elijan un Hangout.', back: 'volver a su Thing', same_brain: 'Same Brain', know_me: 'Know Me', this_or_that: 'This or That', hot: 'Hot',
    sameBrainDescription: 'Elijan por separado y vean si coincidieron.', knowMeDescription: 'Adivina qué eligió la otra persona.',
    thisOrThatDescription: 'Voten a quién le queda mejor.', hotDescription: 'Preguntas de coquetas a picantes, solo al nivel que ambos acepten.',
    chooseLevel: 'elige tu límite para Hot.', privateChoice: 'solo mostramos el nivel compartido.', flirty: 'Coqueto', bold: 'Atrevido', spicy: 'Picante', kitkat: 'KitKat',
    waitingConsent: 'esperando las dos elecciones…', sharedLevel: 'nivel compartido', start: 'empezar →', ourDeck: 'Our Deck',
    ourDeckDescription: 'Creen cartas privadas y después mézclenlas.', makeBatch: 'arma tu tanda.', cardsEach: '3 cartas cada quien.',
    mixed: 'las mezclaremos.', anonymous: 'sin nombres.', addCard: 'agregar carta', finishBatch: 'terminar mi tanda',
    yourCards: 'tus cartas', theirCards: 'sus cartas', waitingBatch: 'esperando la otra tanda…', batchReady: 'las dos tandas están listas.',
    foundation: 'Este Hangout está listo para recibir su juego.', state: 'estado', retry: 'reintentar', busy: 'un momento…',
    sameBrainIntro: 'Ocho elecciones rápidas. Respondan por separado y revelen juntos.', begin: 'same brain →', round: 'ronda',
    waitingPartner: 'esperando a la otra persona…', answerLocked: 'respuesta guardada.', match: 'COINCIDIERON', sameBrain: 'same brain.',
    notThisTime: 'esta vez no.', youPicked: 'elegiste', theyPicked: 'eligió', next: 'la siguiente →',
    finalLine: 'fueron', matched: 'coincidencias', bestStreak: 'mejor racha', seeSpace: 'ver Space', backThing: 'volver al Thing',
    togetherQuestion: '¿están juntos ahora?', together: 'estamos juntos', apart: 'estamos a distancia', contextFixed: 'esto se mantiene durante todo el Hangout.',
    knowMeIntro: 'Ocho predicciones. Túrnense para elegir y adivinar.', thisOrThatIntro: 'Ocho preguntas. Voten en privado a quién le queda cada una.',
    subjectPrompt: '¿qué elegirías?', predictorPrompt: '¿qué crees que eligió?', votePrompt: '¿a quién le queda más?',
    gotIt: 'le atinaste.', missedIt: 'esta no.', agreed: 'coincidieron.', split: 'opiniones divididas.',
    predictions: 'predicciones', correct: 'correctas', agreements: 'acuerdos',
    hotIntro: 'Empieza Coqueto. Para subir el nivel, ambos tienen que aceptar.', completePrompt: 'listo', skip: 'saltar', finishHere: 'terminar aquí',
    wannaBold: '¿quieren subir el nivel?', wannaSpicy: '¿seguimos?', kitkatWait: 'espera…', kitkatMore: 'hay uno más.',
    stayFlirty: 'seguir coquetos', goBold: 'ir a atrevido', stayBold: 'seguir atrevidos', goSpicy: 'ir a picante', openKitkat: 'abrir KitKat', maybeNot: 'mejor no',
    stayingHere: 'nos quedamos aquí :)', levelUp: 'ambos dijeron que sí.', waitingVote: 'esperando su elección privada…', prompts: 'preguntas', reached: 'llegaron a',
    said: 'dijo', youGuessed: 'tú adivinaste', wannaExplain: '¿quieres contar por qué?', addThought: 'agregar una idea', keepGoing: 'seguir →',
    picked: 'eligió', noted: 'anotado.', yourMove: 'tu turno.', useIt: 'úsalo →', answerBack: 'responde →', theirTurn: 'su turno →',
    turn: 'turno de {name}', howWell: '¿qué tanto conoces a {name}?', choosing: '{name} está eligiendo…', whatPicked: '¿qué crees que eligió?', waitingMove: 'esperando la reacción de {name}…',
    rememberThis: '¿recuerdas esto?', youFoundIt: 'lo encontraron.', oneMoreDoor: 'una puerta más.',
  },
} as const;
