export const flowCopy = {
  en: {
    codeOrLink: 'invite code or link',
    invite_expired: 'This invite has expired. Ask for a new link.',
    invite_used: 'This invite has already been accepted. Check your Things.',
    invite_revoked: 'This invite was cancelled or replaced. Ask for a new link.',
    invite_rate_limited: 'Too many invite attempts. Wait a few minutes and try again.',
    thing_full: 'This Thing already has two members.',
    title: 'your things', start: 'start a thing →', join: 'join with invite', invite: 'invite someone',
    startHint: 'Something between two people. Start by inviting someone.', create: 'create invite →',
    pending_invite: 'waiting for them…', pending_charm: 'now make it yours.', active: 'your thing.', disconnected: 'disconnected',
    code: 'invite code', qrLabel: 'QR code for this invite', continue: 'continue →', accept: 'join →', invited: 'wants to start a Thing with you.',
    notNow: 'not now', share: 'share invite', copyLink: 'copy link', copyCode: 'copy code', copied: 'copied',
    copyFailed: 'Could not copy. Select and copy the link below.', expires: 'Expires', expired: 'This invite has expired.',
    renew: 'create a new invite', cancel: 'cancel this thing', pick: 'Pick a Charm to propose.',
    propose: 'propose this Charm →', waiting: 'waiting for them…', personProposed: '{name} chose this Charm.',
    youProposed: 'you proposed this Charm.', keepQuestion: 'keep this Charm?', keepCharm: 'keep it →',
    pickAnother: 'pick another', backProposal: 'back to their proposal',
    cherry: 'cherries', moon: 'moon', spark: 'spark', clover: 'clover', home: 'something between you two.',
    retry: 'try again', busy: 'one moment…', offline: 'You are offline. Reconnect to sync your Thing.',
    session_required: 'Sign in to continue.', profile_required: 'Finish your profile to continue.',
    invite_unavailable: 'This invite is invalid, expired, cancelled, or already used.', own_invite: 'This is your invite. Share it with someone else.',
    thing_unavailable: 'This Thing is unavailable or you are not a member.', proposal_changed: 'The proposal changed. Check the latest Charm.',
    own_proposal: 'The other person needs to accept your proposal.', invalid_charm: 'Choose one of the available Charms.',
    too_many_pending: 'You have 10 pending invitations. Cancel one before starting another.', connection_failed: 'Could not connect. Try again.',
  },
  es: {
    codeOrLink: 'código o enlace de invitación',
    invite_expired: 'Esta invitación venció. Pide un enlace nuevo.',
    invite_used: 'Esta invitación ya se aceptó. Revisa tus Things.',
    invite_revoked: 'Esta invitación se canceló o reemplazó. Pide un enlace nuevo.',
    invite_rate_limited: 'Demasiados intentos de invitación. Espera unos minutos e inténtalo de nuevo.',
    thing_full: 'Este Thing ya tiene dos miembros.',
    title: 'tus things', start: 'empieza un thing →', join: 'unirse con invitación', invite: 'invita a alguien',
    startHint: 'Algo entre dos personas. Empieza invitando a alguien.', create: 'crear invitación →',
    pending_invite: 'esperando a la otra persona…', pending_charm: 'ahora háganlo suyo.', active: 'su thing.', disconnected: 'desconectado',
    code: 'código de invitación', qrLabel: 'Código QR de esta invitación', continue: 'continuar →', accept: 'unirme →', invited: 'quiere empezar un Thing contigo.',
    notNow: 'ahora no', share: 'compartir invitación', copyLink: 'copiar enlace', copyCode: 'copiar código', copied: 'copiado',
    copyFailed: 'No se pudo copiar. Selecciona y copia el enlace de abajo.', expires: 'Vence', expired: 'Esta invitación venció.',
    renew: 'crear otra invitación', cancel: 'cancelar este thing', pick: 'Elige un Charm para proponer.',
    propose: 'proponer este Charm →', waiting: 'esperando…', personProposed: '{name} propuso este Charm.',
    youProposed: 'propusiste este Charm.', keepQuestion: '¿quedarnos con este Charm?', keepCharm: 'quedarnos con este →',
    pickAnother: 'proponer otro', backProposal: 'volver a su propuesta',
    cherry: 'cerezas', moon: 'luna', spark: 'chispa', clover: 'trébol', home: 'algo entre ustedes dos.',
    retry: 'reintentar', busy: 'un momento…', offline: 'Sin conexión. Reconéctate para sincronizar tu Thing.',
    session_required: 'Inicia sesión para continuar.', profile_required: 'Completa tu perfil para continuar.',
    invite_unavailable: 'La invitación no es válida, venció, se canceló o ya se usó.', own_invite: 'Esta es tu invitación. Compártela con alguien más.',
    thing_unavailable: 'Este Thing no está disponible o no eres miembro.', proposal_changed: 'La propuesta cambió. Revisa el Charm más reciente.',
    own_proposal: 'La otra persona debe aceptar tu propuesta.', invalid_charm: 'Elige uno de los Charms disponibles.',
    too_many_pending: 'Tienes 10 invitaciones pendientes. Cancela una antes de empezar otra.', connection_failed: 'No se pudo conectar. Inténtalo de nuevo.',
  },
} as const;
