export const flowCopy = {
  en: {
    codeOrLink: 'invite code or link',
    invite_expired: 'This invite has expired. Ask for a new link.',
    invite_used: 'This invite has already been accepted. Check your Things.',
    invite_revoked: 'This invite was cancelled or replaced. Ask for a new link.',
    invite_rate_limited: 'Too many invite attempts. Wait a few minutes and try again.',
    thing_full: 'This Thing already has two members.',
    title: 'your things', start: 'start a thing →', join: 'join with invite', invite: 'invite someone',
    startHint: 'Something between two people. Start by inviting someone.', create: 'create invite →',
    pending_invite: 'waiting for them…', pending_charm: 'now make it yours.', active: 'your thing.', disconnected: 'disconnected',
    code: 'invite code', qrLabel: 'QR code for this invite', continue: 'continue →', accept: 'join →', invited: 'wants to start a Thing with you.',
    notNow: 'not now', share: 'share invite', copyLink: 'copy link', copyCode: 'copy code', copied: 'copied',
    copyFailed: 'Could not copy. Select and copy the link below.', expires: 'Expires', expired: 'This invite has expired.',
    renew: 'create a new invite', cancel: 'Cancel Thing', pick: 'Pick a Charm to propose.',
    propose: 'propose this Charm →', waiting: 'waiting for them…', personProposed: '{name} chose this Charm.',
    youProposed: 'you proposed this Charm.', keepQuestion: 'keep this Charm?', keepCharm: 'keep it →',
    pickAnother: 'pick another', backProposal: 'back to their proposal',
    cherry: 'cherries', moon: 'moon', spark: 'spark', clover: 'clover', home: 'something between you two.',
    startHangout: 'Start a Hangout', space: 'Space', recentActivity: 'recent activity', pastThings: 'past things',
    nothingYet: 'nothing here yet.', makeSomething: 'start a Hangout and make something happen.',
    quickStats: 'Quick shared stats', hangoutsShort: 'Hangouts', dayStreak: 'day streak', matchesShort: 'matches', matchedShort: 'matched',
    waitingForYou: 'is waiting for you.', inProgress: 'in progress', openHangout: 'Open Hangout', joinHangout: 'Join Hangout', continueHangout: 'Continue Hangout',
    sharedThings: 'our things', sharedThingsEmpty: 'Little shared things will collect here over time.',
    settings: 'Thing settings', changeColor: 'Change color', endThing: 'End this Thing', endTitle: 'End this Thing?',
    endBody: 'You won’t be able to start new Hangouts together.', endConfirm: 'End Thing', close: 'Cancel', ended: 'This Thing has ended.',
    colorCherry: 'Cherry', colorButter: 'Butter', colorElectricBlue: 'Electric blue', colorAcid: 'Acid',
    colorTangerine: 'Tangerine', colorPurple: 'Purple', colorPaper: 'Paper', colorInk: 'Ink',
    retry: 'try again', busy: 'one moment…', offline: 'You are offline. Reconnect to sync your Thing.',
    session_required: 'Sign in to continue.', profile_required: 'Finish your profile to continue.',
    invite_unavailable: 'This invite is invalid, expired, cancelled, or already used.', own_invite: 'This is your invite. Share it with someone else.',
    thing_unavailable: 'This Thing is unavailable or you are not a member.', proposal_changed: 'The proposal changed. Check the latest Charm.',
    own_proposal: 'The other person needs to accept your proposal.', invalid_charm: 'Choose one of the available Charms.',
    invalid_color: 'Choose one of the available colors.', invalid_game_type: 'Choose an available Hangout.',
    invalid_hot_level: 'Choose a Hot level.', invalid_hot_mode: 'That Hot mode is unavailable.', hot_consent_required: 'Both people need to choose a Hot level first.',
    our_deck_unavailable: 'Our Deck opens when both people choose Spicy.', hangout_unavailable: 'This Hangout is unavailable.',
    hangout_in_progress: 'A Hangout is already in progress.',
    invalid_card: 'Write a card up to 240 characters.', batch_full: 'Your three cards are ready.', batch_incomplete: 'Add three cards before finishing your batch.',
    prompt_pack_unavailable: 'Same Brain needs more prompts before it can start.', round_unavailable: 'This round moved on. Refresh to catch up.',
    invalid_answer: 'Choose one of the two answers.', answer_locked: 'Your answer is already locked.',
    too_many_pending: 'You have 10 pending invitations. Cancel one before starting another.', connection_failed: 'Could not connect. Try again.',
  },
  es: {
    codeOrLink: 'código o enlace de invitación',
    invite_expired: 'Esta invitación venció. Pide un enlace nuevo.',
    invite_used: 'Esta invitación ya se aceptó. Revisa tus Things.',
    invite_revoked: 'Esta invitación se canceló o reemplazó. Pide un enlace nuevo.',
    invite_rate_limited: 'Demasiados intentos de invitación. Espera unos minutos e inténtalo de nuevo.',
    thing_full: 'Este Thing ya tiene dos miembros.',
    title: 'tus things', start: 'empieza un thing →', join: 'unirse con invitación', invite: 'invita a alguien',
    startHint: 'Algo entre dos personas. Empieza invitando a alguien.', create: 'crear invitación →',
    pending_invite: 'esperando a la otra persona…', pending_charm: 'ahora háganlo suyo.', active: 'su thing.', disconnected: 'desconectado',
    code: 'código de invitación', qrLabel: 'Código QR de esta invitación', continue: 'continuar →', accept: 'unirme →', invited: 'quiere empezar un Thing contigo.',
    notNow: 'ahora no', share: 'compartir invitación', copyLink: 'copiar enlace', copyCode: 'copiar código', copied: 'copiado',
    copyFailed: 'No se pudo copiar. Selecciona y copia el enlace de abajo.', expires: 'Vence', expired: 'Esta invitación venció.',
    renew: 'crear otra invitación', cancel: 'Cancelar Thing', pick: 'Elige un Charm para proponer.',
    propose: 'proponer este Charm →', waiting: 'esperando…', personProposed: '{name} propuso este Charm.',
    youProposed: 'propusiste este Charm.', keepQuestion: '¿quedarnos con este Charm?', keepCharm: 'quedarnos con este →',
    pickAnother: 'proponer otro', backProposal: 'volver a su propuesta',
    cherry: 'cerezas', moon: 'luna', spark: 'chispa', clover: 'trébol', home: 'algo entre ustedes dos.',
    startHangout: 'Empezar un Hangout', space: 'Space', recentActivity: 'actividad reciente', pastThings: 'things anteriores',
    nothingYet: 'todavía no hay nada.', makeSomething: 'empiecen un Hangout y hagan que pase algo.',
    quickStats: 'Resumen compartido', hangoutsShort: 'Hangouts', dayStreak: 'días de racha', matchesShort: 'coincidencias', matchedShort: 'coincidencias',
    waitingForYou: 'te está esperando.', inProgress: 'en curso', openHangout: 'Abrir Hangout', joinHangout: 'Unirme al Hangout', continueHangout: 'Continuar Hangout',
    sharedThings: 'cosas de ustedes', sharedThingsEmpty: 'Aquí se irán juntando sus pequeñas cosas compartidas.',
    settings: 'Ajustes del Thing', changeColor: 'Cambiar color', endThing: 'Terminar este Thing', endTitle: '¿Terminar este Thing?',
    endBody: 'Ya no podrán empezar nuevos Hangouts juntos.', endConfirm: 'Terminar Thing', close: 'Cancelar', ended: 'Este Thing terminó.',
    colorCherry: 'Cereza', colorButter: 'Mantequilla', colorElectricBlue: 'Azul eléctrico', colorAcid: 'Ácido',
    colorTangerine: 'Mandarina', colorPurple: 'Morado', colorPaper: 'Papel', colorInk: 'Tinta',
    retry: 'reintentar', busy: 'un momento…', offline: 'Sin conexión. Reconéctate para sincronizar tu Thing.',
    session_required: 'Inicia sesión para continuar.', profile_required: 'Completa tu perfil para continuar.',
    invite_unavailable: 'La invitación no es válida, venció, se canceló o ya se usó.', own_invite: 'Esta es tu invitación. Compártela con alguien más.',
    thing_unavailable: 'Este Thing no está disponible o no eres miembro.', proposal_changed: 'La propuesta cambió. Revisa el Charm más reciente.',
    own_proposal: 'La otra persona debe aceptar tu propuesta.', invalid_charm: 'Elige uno de los Charms disponibles.',
    invalid_color: 'Elige uno de los colores disponibles.', invalid_game_type: 'Elige un Hangout disponible.',
    invalid_hot_level: 'Elige un nivel de Hot.', invalid_hot_mode: 'Ese modo de Hot no está disponible.', hot_consent_required: 'Ambas personas deben elegir primero un nivel de Hot.',
    our_deck_unavailable: 'Our Deck aparece cuando ambos eligen Spicy.', hangout_unavailable: 'Este Hangout no está disponible.',
    hangout_in_progress: 'Ya hay un Hangout en curso.',
    invalid_card: 'Escribe una carta de hasta 240 caracteres.', batch_full: 'Tus tres cartas están listas.', batch_incomplete: 'Agrega tres cartas antes de terminar tu tanda.',
    prompt_pack_unavailable: 'Same Brain necesita más preguntas antes de empezar.', round_unavailable: 'Esta ronda ya avanzó. Actualiza para continuar.',
    invalid_answer: 'Elige una de las dos respuestas.', answer_locked: 'Tu respuesta ya quedó guardada.',
    too_many_pending: 'Tienes 10 invitaciones pendientes. Cancela una antes de empezar otra.', connection_failed: 'No se pudo conectar. Inténtalo de nuevo.',
  },
} as const;
