export const flowCopy = {
  en: {
    codeOrLink: 'invite code or link',
    invite_expired: 'This invite has expired. Ask for a new link.',
    invite_used: 'This invite has already been accepted. Check your Things.',
    invite_revoked: 'This invite was cancelled or replaced. Ask for a new link.',
    thing_full: 'This Thing already has two members.',
    title: 'your things', start: 'start a thing →', join: 'join with invite', invite: 'invite someone',
    startHint: 'Something between two people. Start by inviting someone.', create: 'create invite →',
    pending_invite: 'waiting for them…', pending_charm: 'now make it yours.', active: 'your thing.', disconnected: 'disconnected',
    code: 'invite code', continue: 'continue →', accept: 'join →', invited: 'wants to start a Thing with you.',
    notNow: 'not now', share: 'share invite', copyLink: 'copy link', copyCode: 'copy code', copied: 'copied',
    copyFailed: 'Could not copy. Select and copy the link below.', expires: 'Expires', expired: 'This invite has expired.',
    renew: 'create a new invite', cancel: 'cancel this thing', pick: 'Choose a Charm. Your choices stay hidden until you both choose.',
    confirm: 'confirm choice →', waiting: 'Your choice is saved. Waiting for them…', partnerReady: 'They have chosen. Your turn.',
    mismatch: 'Different choices last round. Both of you can choose again.', round: 'Round',
    cherry: 'cherries', moon: 'moon', spark: 'spark', clover: 'clover', home: 'something between you two.',
    retry: 'try again', busy: 'one moment…', offline: 'You are offline. Reconnect to sync your Thing.',
    session_required: 'Sign in to continue.', profile_required: 'Finish your profile to continue.',
    invite_unavailable: 'This invite is invalid, expired, cancelled, or already used.', own_invite: 'This is your invite. Share it with someone else.',
    thing_unavailable: 'This Thing is unavailable or you are not a member.', round_changed: 'The round has changed. Check the latest state and choose again.',
    invalid_charm: 'Choose one of the available Charms.', already_chosen: 'Your choice is already saved for this round.',
    too_many_pending: 'You have 10 pending invitations. Cancel one before starting another.', connection_failed: 'Could not connect. Try again.',
  },
  es: {
    codeOrLink: 'código o enlace de invitación',
    invite_expired: 'Esta invitación venció. Pide un enlace nuevo.',
    invite_used: 'Esta invitación ya se aceptó. Revisa tus Things.',
    invite_revoked: 'Esta invitación se canceló o reemplazó. Pide un enlace nuevo.',
    thing_full: 'Este Thing ya tiene dos miembros.',
    title: 'tus things', start: 'empieza un thing →', join: 'unirse con invitación', invite: 'invita a alguien',
    startHint: 'Algo entre dos personas. Empieza invitando a alguien.', create: 'crear invitación →',
    pending_invite: 'esperando a la otra persona…', pending_charm: 'ahora háganlo suyo.', active: 'su thing.', disconnected: 'desconectado',
    code: 'código de invitación', continue: 'continuar →', accept: 'unirme →', invited: 'quiere empezar un Thing contigo.',
    notNow: 'ahora no', share: 'compartir invitación', copyLink: 'copiar enlace', copyCode: 'copiar código', copied: 'copiado',
    copyFailed: 'No se pudo copiar. Selecciona y copia el enlace de abajo.', expires: 'Vence', expired: 'Esta invitación venció.',
    renew: 'crear otra invitación', cancel: 'cancelar este thing', pick: 'Elijan un Charm. Sus elecciones permanecen ocultas hasta que ambos elijan.',
    confirm: 'confirmar elección →', waiting: 'Tu elección está guardada. Esperando a la otra persona…', partnerReady: 'La otra persona ya eligió. Te toca.',
    mismatch: 'Eligieron distinto en la ronda anterior. Vuelvan a elegir.', round: 'Ronda',
    cherry: 'cerezas', moon: 'luna', spark: 'chispa', clover: 'trébol', home: 'algo entre ustedes dos.',
    retry: 'reintentar', busy: 'un momento…', offline: 'Sin conexión. Reconéctate para sincronizar tu Thing.',
    session_required: 'Inicia sesión para continuar.', profile_required: 'Completa tu perfil para continuar.',
    invite_unavailable: 'La invitación no es válida, venció, se canceló o ya se usó.', own_invite: 'Esta es tu invitación. Compártela con alguien más.',
    thing_unavailable: 'Este Thing no está disponible o no eres miembro.', round_changed: 'La ronda cambió. Revisa el estado y elige de nuevo.',
    invalid_charm: 'Elige uno de los Charms disponibles.', already_chosen: 'Tu elección ya está guardada para esta ronda.',
    too_many_pending: 'Tienes 10 invitaciones pendientes. Cancela una antes de empezar otra.', connection_failed: 'No se pudo conectar. Inténtalo de nuevo.',
  },
} as const;
